### ISSUE TITLE
glucifer colour bar

### ISSUE THREAD

**Issue by garethkennedy** [underworldcode/underworld2#35]
Need to specify no colour bar for a vector arrow plot object added after a surface object. If you don't then the colour bar will be the default colours (blue to orange) rather than the surface colours (blue white red). Below example is working version of a cell in "docs/tutorials/1_02_Convection_Example.ipynb". 

figWithV = glucifer.Figure(figsize=(800,400))
figWithV + glucifer.objects.Surface(mesh, temperatureField, colours="blue white red")
figWithV + glucifer.objects.VectorArrows(mesh, velocityField, arrowHeadSize=0.2, lengthScale=0.2, colourBar=False)
figWithV.show()

Better if we can get the colour bar from a vector arrow object to not overwrite previous colour bars.

**Comment by garethkennedy** [comment]
Also related to the recent glucifer update. The mesh object doesn't actually draw the mesh. It does the node numbering but no mesh lines.

**Comment by jmansour** [comment]
Not sure about if there's an issue with multiple colourbars, but I've disabled the colourbar for the VectorArrows object.  It has no need for a colourbar.   

I believe when there's multiple colourbars, they should all be displayed.  But haven't tested this. 

As for the mesh, i'm not having issues at this end.  So anytime you try and use the Mesh drawing object, you simply get nothing (except possibly node numbers)?

**Comment by garethkennedy** [comment]
Yeah. All my mesh examples are only outputting numbers and no lines.

**Comment by OKaluza** [comment]
I can't duplicate this one either, mesh lines are coming out fine

Yes multiple colour bars can be displayed but will possibly need to play
with the "margin" property so they aren't drawn on top of each other

On 1 December 2015 at 14:27, Gareth Kennedy <notifications@github.com>
wrote:

> Yeah. All my mesh examples are only outputting numbers and no lines.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/underworldcode/underworld2/issues/35#issuecomment-160838940>
> .
>



-- 
Owen Kaluza <owen.kaluza@monash.edu>
Senior Visualisation Specialist, eResearch Support
Monash University, Clayton Campus, Rm.318, Building 82
Phone: 03 9902 9809, Mobile: 0410 545 824

**Comment by garethkennedy** [comment]
The lines still aren't showing up (as seen by John). Interestingly enough the lines are visible when you show via the webgl.

**Comment by jmansour** [comment]
gareth, does the mesh show in any figures?  i notice that on the latest update, my mesh shows as white lines.  also, i'm finding the colours are different when i use 'save_image' as opposed to 'show'.  the 'save_image' colours seem the same as when webgl is used. 

<img width="916" alt="screen shot 2015-12-02 at 8 58 57 pm" src="https://cloud.githubusercontent.com/assets/1439389/11528047/6f05ad02-9938-11e5-884c-886e73d72d61.png">
<img width="1032" alt="screen shot 2015-12-02 at 9 00 36 pm" src="https://cloud.githubusercontent.com/assets/1439389/11528033/60b5dc54-9938-11e5-824b-6c95c21c1c12.png">

![saveimage](https://cloud.githubusercontent.com/assets/1439389/11528001/35bccd82-9938-11e5-9fe6-73ded8529d01.png)

**Comment by OKaluza** [comment]
I think latest changes in LavaVu (https://github.com/OKaluza/LavaVu/commit/18e4fcff4372e7615bcde791dabe24283121b788) should fix the lines issues. I enabled line anti-aliasing to improve the line rendering but looks like it caused a few problems on some OpenGL drivers. 
If this fix doesn't help, it can be disabled with `Mesh(..., properties={"linesmooth" : False})`

The colours issue looks like red/blue being swapped somewhere but I'll have to look at that next week as I can't duplicate it here. Which of those is the correct colours for your colour map?

**Comment by jmansour** [comment]
All of the above were produced using the default colour map.   When I put it colour name (eg "red blue white"), it seems to work correctly, but with hex colours ("#288FD0 #50B6B8 #989878 #C68838 #FF7520") i'm getting the inconsistent results.  Strange.

Your change for the lines issues made a difference, but still not quiet right:

![bingo](https://cloud.githubusercontent.com/assets/1439389/11546151/947136c6-999f-11e5-91eb-09efc1efd0f1.png)

I'll set that mesh properties option (linesmooth:false) as default for now.

**Comment by jmansour** [comment]
Another thing requiring some tuning.... the Figure edge __conflicts__ with the mesh viewer.. this is what causes the bold looking figure edges.  

edgecolour='white':
![whiteedge](https://cloud.githubusercontent.com/assets/1439389/11546294/7eba1036-99a0-11e5-8f1c-e77ca56d3b7f.png)

edgecolour='black'
![blackedge](https://cloud.githubusercontent.com/assets/1439389/11546298/88f5cc84-99a0-11e5-89d3-c050a3a9707b.png)

I think this is only evident with linesmoothing off however.

**Comment by jmansour** [comment]
lol.. actually, notice there's also a colour difference above!  indeed, running the identical viz results in the colourmap switching around every time!  

```
figtemp = glucifer.Figure( figsize=(800,400), edgecolour='black' )
figtemp + glucifer.objects.Surface( mesh, temperatureField)
figtemp + glucifer.objects.Mesh( mesh )
figtemp.show()
figtemp.save_image("blackedge5")
```

**Comment by OKaluza** [comment]
Ok, the hex colour parsing is fixed and committed.

Everything else is just aliasing, you have the choice of aliasing artifacts (border edge, some lines thicker than others etc) or drawing anti-aliased blended lines which will produce less artifacts but the lines will be fainter due to of blending sub-pixel lines.

To control this switch the linesmooth property on/off, current default is on, I think it looks nicer:
glucifer.objects.Mesh(mesh, nodeNumbers=True, properties={"linewidth" : 1.0, "linesmooth" : True/False})

(you can also make them wider with the "linewidth" property if you want more solid smooth lines) 

And that's it I'm outta here.. P.S: I'm closing this issue as it's getting a bit out of control, this lines stuff should have been a separate issue. If there's still problems open a new one.

**Comment by jmansour** [comment]
no probs owen!  wasn't expecting you to sort it today or anything, but thanks!

**Comment by OKaluza** [comment]
No worries, it was an easy fix. The line aliasing stuff has been revisited many times, it's just the way it is with OpenGL. To get improved results I'd have to implement something like this https://www.mapbox.com/blog/drawing-antialiased-lines/ but as line plotting was never the main focus or a huge priority in the past it has not seemed worth the trouble.
